spring:
    application:
        name: pricing_service

    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;LOCK_MODE=0
        driver-class-name: org.h2.Driver
        username: sa
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        defer-datasource-initialization: true
        properties:
            hibernate:
                ddl-auto: create-drop
                format_sql: true
                use_sql_comments: true

    h2:
        console:
            enabled: true
            path: /h2-console

    sql:
        init:
            mode: always
            transactional: false
            data-locations: classpath:data.sql

server:
    port: 8080

logging:
    level:
        com.zara.pricing_service: DEBUG
        org.springframework.rest: DEBUG
        org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE